### ISSUE TITLE
Feedback on proposal

### ISSUE THREAD

**Issue by martinsson** [quara-dev/letsgo-nats#1]
This proposal solves the problem indeed.

I like 
* it uses the acme standard protocol
* it is quite small so quite effective
* it describes the alternatives well

Questions
* What's the problem with the third alternative. It's described but the drawbacks are not mentioned
```
When deploying NATS server using Docker, it's possible to rely on a similar solution than with systemd. Use volumes to mount certificates into the container, and when new certificates are received instead of sending a SIGHUP signal to NATS server directly, restart the docker container, or exec into the container in order to send a SIGHUP signal.
```
* Why not run it as a separate process? Responsible for testing the validity before pushing it to the server
* Is it possible to create a plugin for an existing certification renewal daemon, similar to what cert-manager does for k8s?

Ideas
* post the new certificate to the server using a queue
* Post an issue at the nats-server repo to discuss this with the majority of nats users and maintainers.

**Comment by charbonnierg** [comment]
I saw that an issue already existed on nats-server repo so I added a comment: https://github.com/nats-io/nats-server/issues/1893

**Comment by charbonnierg** [comment]
Regarding the question:

> What's the problem with the third alternative. It's described but the drawbacks are not mentioned

I gave more detail in my comment on nats-server repo:

> In our projects, we use Traefik to automate almost all certificates generation and renewals (regardless of deployment environment), but because of NATS, we still need [certbot](https://certbot.eff.org/) or [lego](https://github.com/go-acme/lego) to run somewhere. When we have access to the host machine, this is fine, but when running in Azure Container Instances (or other container platforms), it means that we need to deploy another container (which means additional cost and complexity).

So the biggest consequence of using a tool such as [lego](https://github.com/go-acme/lego) or [certbot](https://certbot.eff.org/) is that is requires running an additional container in cloud environments. Moreover, this container must share a volume with the container running nats-server, or use some mechanism to upload new certificates into the container.

When we have control over the host system running docker (for example edge environments), things are simpler.

**Comment by charbonnierg** [comment]
> Why not run it as a separate process? Responsible for testing the validity before pushing it to the server

Because it requires running an additional container in cloud environments, as well as volumes or knowledge of nats-server container name in order to `docker cp`. This is not "impossible" at all, and we already did that in the past. It's just that it's additional friction.

> post the new certificate to the server using a queue

Running another process which communicates using NATS is not (IMHO) a good solution (for example using a subscription as a queue like you proposed) because we use JWT authentication, and thus any client requires credentials to connect.

One of the feature I love with NATS, is the ability to deploy a server with authentication enabled, but without any credential (only JWT are used to deploy the server) ! If administrators need valid credentials in order to deploy certificate renewal process, it would only make deployment operation more complex.

> Is it possible to create a plugin for an existing certification renewal daemon, similar to what cert-manager does for k8s?

Maybe, I'm not sure I understand what do you mean by "plugin". But the original problem I tried to address is the following:

I'm trying to make it even more easier for small project without dedicated IT team to deploy nats-server with TLS enabled running for months.

The target audience is people who do not even have knowledge about tools like certbot or lego. Ideally, the only knowledge required should be:

- Which **email** should be used to get notified when certificates will expire ?
- What are the **domain names** on which nats-server will be served ?
- Which **DNS provider** should be used when dns-01 challenge is used, in other words, which DNS provider is used to manage DNS records ?
- What are the **DNS provider credentials** ?

Those 4 parameters have nothing to do with NATS, and are fairly easy to understand (in the POC, DNS provider is always **digitalocean**, so only 3 parameters are required.)
